### PR TITLE
Add appveyor.yml file

### LINKED ISSUE #21: Add windows builds with Appveyor

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #21

### CODE REVIEW

**Comment by nicoddemus** [comment]
Argh that's why it is recommended to use a fork instead of committing directly to the repository: you get double the builds. 👎

**Comment by gqmelo** [comment]
> Argh that's why it is recommended to use a fork instead of committing directly to the repository: you get double the builds. 

Yeah, this sucks, only CircleCI does it right.

**Comment by nicoddemus** [comment]
The first AppVeyor build that failed can be ignored, I cancelled it.

**Comment by prusse-martin** [comment]
On qmxgraph (using only travis-ci atm) builds are triggered only on actual PRs and master (not for every commit). It is this way mostly because simple branch creation was triggering builds.

**Pull request merged**
